language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - rbx-2
  - jruby-19mode

gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile

script: 
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rspec
  - bundle exec rubocop

notifications:
  email:
    on_success: never
  slack:
    rooms:
      secure: eWi2ge1YhYhHAhMYlLtvh2E/TzIZ5eq7oX+HA57SjNzGiy0tp7ETbvdh4SWaFcZZi6JZjL919toX1E8Wt+tb7ZSJUm/fDOsra42SX28n/V6psrc2MzuavKRt5JcUw198pcV9K/LKzxGCOqsTpfOe1hiTPsLtZsZi7bgyRKf4b3VP9VH12duGRYBe+L0bY65O2yINNpNzDw8HsDQM2mnwS+jxPJW/7GEO5Gyl9G5yPNPnSFlshWhgt6gPS/9ty33zzJ4NBweR1A8BCIytxgAqemSnbofp6jXs1oEdQ5swyMTtn8z5s49cBC7mQlHDnSdBQXsWp4HT5GqU5gVKGlHA/L5Or7GrpX+QqQ+AFF6i3dYhafX3cZ1kMPQBI+7747RepAX4QgDrnoLBRJEpmTO/irFJ3rdNtOAQvXGLXI7hfSyTFbbl8fNaaXB93D0YmTStSJc1Z+bPT69qHJZkcBp1/NZ+guGOKQ77x6E0gYulG2szmSSQ2miFXUCBAloonEVEXniPXnO04uvD66v16ocVAJth/C9bsIpFj79mdfpNfjByg9vtN0bpxYXUreY+Dfkpn+DwLqyFZRYXLhGx1s0cCzrU5y/xP8zOPH90yma6bqKTvBzfZDGLHSLtx3+jez7ReqGBL965ZM2/vR+fCRlS6rvA8WkuJbgn3y5HAbD9MlQ=
      on_success: never
