language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - rbx-2
  - jruby-19mode

cache: bundler

script: 
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rspec
  - bundle exec rubocop

notifications:
  email:
    on_success: never